version: '3'

services:
  #  app:db
  db: 
    container_name: mean_db
    image: mongo:5.0.16
    volumes:
      - ./mongo:/data/db
    ports:
      - 27017:27017
      # el puerto de la app : que sea igual al de la pc
    restart: always